"""Add service and relationship

Revision ID: 0125d48f3055
Revises: 1b05fdfaec4a
Create Date: 2026-03-09 15:55:55.452651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0125d48f3055'
down_revision: Union[str, Sequence[str], None] = '1b05fdfaec4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('due_configs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_transactions',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('payment_type', sa.Enum('tithe', 'dues', 'donation', name='paymenttype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('online', 'manual', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='paymentstatus'), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('paystack_reference', sa.String(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_finance_transactions_reference'), 'finance_transactions', ['reference'], unique=True)
    op.create_table('profile_finance_stats',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('total_tithes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_dues', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_donations', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pending_transactions', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_finance_stats')
    op.drop_index(op.f('ix_finance_transactions_reference'), table_name='finance_transactions')
    op.drop_table('finance_transactions')
    op.drop_table('due_configs')
    # ### end Alembic commands ###
