"""Update profile and finance

Revision ID: 6392dd5294d5
Revises: e4e0d0e34347
Create Date: 2026-03-09 18:11:00.376481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6392dd5294d5'
down_revision: Union[str, Sequence[str], None] = 'e4e0d0e34347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_transactions', sa.Column('profile_name', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'finance_transactions', 'profiles', ['profile_name'], ['fullname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_transactions', type_='foreignkey')
    op.drop_column('finance_transactions', 'profile_name')
    # ### end Alembic commands ###
