"""fix timestamp defaults

Revision ID: cf3307e0be85
Revises: 8c250cca8b3e
Create Date: 2026-02-27 01:24:53.783262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3307e0be85'
down_revision: Union[str, Sequence[str], None] = '8c250cca8b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_group'), 'group_members', type_='unique')
    op.create_index('ix_group_member_group_status', 'group_members', ['group_id', 'status'], unique=False)
    op.create_unique_constraint('uq_user_single_group', 'group_members', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_single_group', 'group_members', type_='unique')
    op.drop_index('ix_group_member_group_status', table_name='group_members')
    op.create_unique_constraint(op.f('uq_user_group'), 'group_members', ['user_id', 'group_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
