"""Adding equipments table

Revision ID: d00fa18465aa
Revises: 97d16bf1600d
Create Date: 2026-03-03 03:04:44.515417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00fa18465aa'
down_revision: Union[str, Sequence[str], None] = '97d16bf1600d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_members_approved_by'), 'group_members', ['approved_by'], unique=False)
    op.drop_constraint(op.f('group_members_approved_by_fkey'), 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'user', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_groups_leader_id'), 'groups', ['leader_id'], unique=False)
    op.drop_column('groups', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_groups_leader_id'), table_name='groups')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(op.f('group_members_approved_by_fkey'), 'group_members', 'user', ['approved_by'], ['id'])
    op.drop_index(op.f('ix_group_members_approved_by'), table_name='group_members')
    op.drop_table('equipments')
    # ### end Alembic commands ###
