"""Fixed service time issues

Revision ID: d8035109a47d
Revises: 6392dd5294d5
Create Date: 2026-03-10 02:39:53.483211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8035109a47d'
down_revision: Union[str, Sequence[str], None] = '6392dd5294d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('grace_before_minutes', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('grace_after_minutes', sa.Integer(), nullable=False))
    op.drop_column('services', 'grace_end_time')
    op.drop_column('services', 'grace_before_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('grace_before_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('grace_end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('services', 'grace_after_minutes')
    op.drop_column('services', 'grace_before_minutes')
    # ### end Alembic commands ###
