"""Add service and relationship

Revision ID: e4e0d0e34347
Revises: 0125d48f3055
Create Date: 2026-03-09 16:44:26.105415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e0d0e34347'
down_revision: Union[str, Sequence[str], None] = '0125d48f3055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finance_transactions', 'profile_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('finance_transactions', 'recorded_by',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('finance_transactions_profile_id_fkey'), 'finance_transactions', type_='foreignkey')
    op.drop_constraint(op.f('finance_transactions_recorded_by_fkey'), 'finance_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'finance_transactions', 'profiles', ['profile_id'], ['user_id'])
    op.create_foreign_key(None, 'finance_transactions', 'profiles', ['recorded_by'], ['user_id'])
    op.alter_column('profile_finance_stats', 'profile_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('profile_finance_stats_profile_id_fkey'), 'profile_finance_stats', type_='foreignkey')
    op.create_foreign_key(None, 'profile_finance_stats', 'profiles', ['profile_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile_finance_stats', type_='foreignkey')
    op.create_foreign_key(op.f('profile_finance_stats_profile_id_fkey'), 'profile_finance_stats', 'profiles', ['profile_id'], ['id'])
    op.alter_column('profile_finance_stats', 'profile_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'finance_transactions', type_='foreignkey')
    op.drop_constraint(None, 'finance_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('finance_transactions_recorded_by_fkey'), 'finance_transactions', 'profiles', ['recorded_by'], ['id'])
    op.create_foreign_key(op.f('finance_transactions_profile_id_fkey'), 'finance_transactions', 'profiles', ['profile_id'], ['id'])
    op.alter_column('finance_transactions', 'recorded_by',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('finance_transactions', 'profile_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
